messages:
  reload-config: '&6&lPromocodes &8&l| &7Конфигурация плагина перезагружена!'
  no-uses: '&6&lPromocodes &8&l| &cУ промокода закончились использования!'
  invalid-promocode: '&6&lPromocodes &8&l| &cПромокод не существует!'
  succes-created: '&6&lPromocodes &8&l| &7Промокод успешно создан!'
  succes-deleted: '&6&lPromocodes &8&l| &7Промокод успешно удалён'
  succes-used: '&6&lPromocodes &8&l| &7Промокод успешно использован!'
  already-used: '&6&lPromocodes &8&l| &cВы уже использовали данный промокод!'
  already-created: '&6&lPromocodes &8&l| &cДанный промокод уже существует!'
  promocode-list: '&6&lPromocodes &8&l| &7Список промокодов'
  no-promocode-list: '&6&lPromocodes &8&l| &cСписок промокодов пуст!'
  add-command: '&6&lPromocodes &8&l| &7Команда успешно добавлена!'
  del-command: '&6&lPromocodes &8&l| &cКоманда успешно удалена!'
  no-command: '&6&lPromocodes &8&l| &7Команда с таким номером не найдена!'
  no-int: '&6&lPromocodes &8&l| &cВведёное вами количество использований не является целым числом!'
  promocode-info:
    - '&6&lPromocodes &8&l| &7Информация по промокоду'
    - '&7Название: &f%promocode%'
    - '&7Использований: &f%uses-amount%/%uses-start%'
    - '&7Дата создания: &f%date%'
    - '&7Список команд:'
  help-player:
    - '&6&lPromocodes &8&l| &7Помощь'
    - '&7/promocode [промокод] - &fАктивировать промокод'
  help-admin:
    - '&6&lPromocodes &8&l| &7Помощь'
    - '&7/promocode [промокод] - &fАктивировать промокод'
    - '&7/promocode create [промокод] [использования] [команда] - &fСоздать промокод'
    - '&7/promocode delete [промокод] - &fУдалить промокод'
    - '&7/promocode info [промокод] - &fИнформация по промокоду'
    - '&7/promocode list - &fСписок промокодов'
    - '&7/promocode addcmd [промокод] [команда] - &fДобавить команду промокоду'
    - '&7/promocode delcmd [промокод] [номер] - &fУдалить команду промокоду'
promocodes: {}
